<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <AssemblyName>Ser2Net.Service</AssemblyName>
    <Product>Ser2Net</Product>
    <Company>Ser2Net</Company>
    <Description>Ser2Net Windows Service</Description>
    <Copyright>Copyright (c) Ser2Net contributors</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ser2Net.Windows.Core\Ser2Net.Windows.Core.csproj" />
  </ItemGroup>
</Project>
