using System.Text;
using System.Text.RegularExpressions;

namespace Ser2Net.Windows.Core;

public static class Ser2NetConfigGenerator
{
    public static string Generate(IEnumerable<ResolvedMapping> mappings)
    {
        var sb = new StringBuilder();
        sb.AppendLine("%YAML 1.1");
        sb.AppendLine("---");
        sb.AppendLine("# Generated by Ser2Net.Service.exe. Edit mappings.json instead of this file.");

        var count = 0;
        foreach (var item in mappings) {
            count++;
            var name = AnchorName(item.Mapping.Name, count);
            var accepter = BuildAccepter(item.Mapping.Tcp);
            var connector = BuildConnector(item.Device.PortName, item.Mapping.Serial);

            sb.AppendLine($"connection: &{name}");
            sb.AppendLine($"  accepter: {accepter}");
            sb.AppendLine($"  connector: {connector}");
            sb.AppendLine("  options:");
            sb.AppendLine($"    max-connections: {Math.Max(1, item.Mapping.Tcp.MaxConnections)}");
            if (!string.IsNullOrWhiteSpace(item.Mapping.Banner)) {
                sb.AppendLine($"    banner: {YamlSingleQuoted(NormalizeBanner(item.Mapping.Banner))}");
            }
            sb.AppendLine();
        }

        if (count == 0) {
            sb.AppendLine("# No enabled mappings resolved to a present serial device.");
        }

        return sb.ToString();
    }

    public static void WriteConfig(string path, IEnumerable<ResolvedMapping> mappings)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, Generate(mappings));
    }

    private static string BuildAccepter(TcpEndpoint tcp)
    {
        var mode = string.IsNullOrWhiteSpace(tcp.Mode) ? "telnet" : tcp.Mode.Trim().ToLowerInvariant();
        return mode == "raw" || mode == "tcp"
            ? $"tcp,{tcp.ListenAddress},{tcp.Port}"
            : $"telnet,tcp,{tcp.ListenAddress},{tcp.Port}";
    }

    private static string BuildConnector(string portName, SerialSettings settings)
    {
        var suffix = $"{settings.Baud}{settings.Settings}".ToUpperInvariant();
        var options = settings.Options.Length == 0 ? "" : " " + string.Join(" ", settings.Options);
        return $"serialdev,{portName},{suffix}{options}";
    }

    private static string AnchorName(string name, int fallback)
    {
        var value = Regex.Replace(name.ToLowerInvariant(), "[^a-z0-9_-]+", "-").Trim('-');
        return string.IsNullOrWhiteSpace(value) ? $"mapping-{fallback}" : value;
    }

    private static string NormalizeBanner(string banner) =>
        banner.Replace("\r\n", "\\r\\n").Replace("\n", "\\r\\n").Replace("\r", "\\r\\n");

    private static string YamlSingleQuoted(string value) => $"'{value.Replace("'", "''")}'";
}
