<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <AssemblyName>Ser2Net.Tray</AssemblyName>
    <Product>Ser2Net</Product>
    <Company>Ser2Net</Company>
    <Description>Ser2Net Windows Manager</Description>
    <Copyright>Copyright (c) Ser2Net contributors</Copyright>
    <ApplicationIcon>Assets\Ser2Net.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ser2Net.Windows.Core\Ser2Net.Windows.Core.csproj" />
  </ItemGroup>
</Project>
